<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0-windows;net45</TargetFrameworks>
	<LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>XListView</Title>
    <Description>XListView is an ordinary WinForms listview component, but with less flicker, hopefully :-) It exposes the protected DoubleBuffer property of the base class.</Description>
    <Copyright>(c) 2025, Adrian Petrila, YO3GFH</Copyright>
    <PackageTags>listview;flicker;common controls</PackageTags>
    <PackageReleaseNotes>Initial release</PackageReleaseNotes>
    <Authors>Adrian Petrila, YO3GFH</Authors>
    <PackageIcon>XListView.png</PackageIcon>
    <ErrorReport>none</ErrorReport>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/yo3gfh/XListView2</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows|AnyCPU'">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows|AnyCPU'">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="XListView.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
